// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"member/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/addSysMember",
				Handler: AddSysMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/deleteSysMember",
				Handler: DeleteSysMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/queryPageSysMemberList",
				Handler: QueryPageSysMemberListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/querySysMemberDetail",
				Handler: QuerySysMemberDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/querySysMemberList",
				Handler: QuerySysMemberListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateSysMember",
				Handler: UpdateSysMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateSysMemberStatus",
				Handler: UpdateSysMemberStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/system/member"),
	)
}
