// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: member.proto

package server

import (
	"context"

	"member/rpc/internal/logic"
	"member/rpc/internal/svc"
	"member/rpc/pb"
)

type MemberServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMemberServer
}

func NewMemberServer(svcCtx *svc.ServiceContext) *MemberServer {
	return &MemberServer{
		svcCtx: svcCtx,
	}
}

// 添加用户
func (s *MemberServer) CreateMember(ctx context.Context, in *pb.MemberData) (*pb.CodeMessageResult, error) {
	l := logic.NewCreateMemberLogic(ctx, s.svcCtx)
	return l.CreateMember(in)
}

// 删除用户
func (s *MemberServer) DeleteMember(ctx context.Context, in *pb.DeleteMemberIds) (*pb.CodeMessageResult, error) {
	l := logic.NewDeleteMemberLogic(ctx, s.svcCtx)
	return l.DeleteMember(in)
}

// 更新用户
func (s *MemberServer) UpdateMember(ctx context.Context, in *pb.MemberData) (*pb.CodeMessageResult, error) {
	l := logic.NewUpdateMemberLogic(ctx, s.svcCtx)
	return l.UpdateMember(in)
}

// 查询用户详情（通过id）
func (s *MemberServer) GetMemberDetailById(ctx context.Context, in *pb.QueryMemberDetailById) (*pb.MemberData, error) {
	l := logic.NewGetMemberDetailByIdLogic(ctx, s.svcCtx)
	return l.GetMemberDetailById(in)
}

// 查询用户详情（通过用户名）
func (s *MemberServer) GetMemberDetailByUsername(ctx context.Context, in *pb.QueryMemberDetailByUsername) (*pb.MemberData, error) {
	l := logic.NewGetMemberDetailByUsernameLogic(ctx, s.svcCtx)
	return l.GetMemberDetailByUsername(in)
}

// 查询用户分页列表
func (s *MemberServer) GetKeywordPageMemberList(ctx context.Context, in *pb.QueryPageMemberList) (*pb.QueryPageMemberListResult, error) {
	l := logic.NewGetKeywordPageMemberListLogic(ctx, s.svcCtx)
	return l.GetKeywordPageMemberList(in)
}
