// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: member.proto

package server

import (
	"context"

	"member/rpc/internal/logic"
	"member/rpc/internal/svc"
	"member/rpc/pb"
)

type MemberServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMemberServer
}

func NewMemberServer(svcCtx *svc.ServiceContext) *MemberServer {
	return &MemberServer{
		svcCtx: svcCtx,
	}
}

// 添加用户
func (s *MemberServer) AddMember(ctx context.Context, in *pb.AddMemberReq) (*pb.AddMemberResp, error) {
	l := logic.NewAddMemberLogic(ctx, s.svcCtx)
	return l.AddMember(in)
}

// 添加用户
func (s *MemberServer) AddMemberWithUsernamePassword(ctx context.Context, in *pb.AddMemberWithUsernamePasswordReq) (*pb.AddMemberWithUsernamePasswordResp, error) {
	l := logic.NewAddMemberWithUsernamePasswordLogic(ctx, s.svcCtx)
	return l.AddMemberWithUsernamePassword(in)
}

// 删除用户
func (s *MemberServer) DeleteMember(ctx context.Context, in *pb.DeleteMemberReq) (*pb.DeleteMemberResp, error) {
	l := logic.NewDeleteMemberLogic(ctx, s.svcCtx)
	return l.DeleteMember(in)
}

// 更新用户
func (s *MemberServer) UpdateMember(ctx context.Context, in *pb.UpdateMemberReq) (*pb.UpdateMemberResp, error) {
	l := logic.NewUpdateMemberLogic(ctx, s.svcCtx)
	return l.UpdateMember(in)
}

// 更新用户状态
func (s *MemberServer) UpdateMemberStatus(ctx context.Context, in *pb.UpdateMemberStatusReq) (*pb.UpdateMemberStatusResp, error) {
	l := logic.NewUpdateMemberStatusLogic(ctx, s.svcCtx)
	return l.UpdateMemberStatus(in)
}

// 查询用户详情（通过id）
func (s *MemberServer) QueryMemberDetail(ctx context.Context, in *pb.QueryMemberDetailReq) (*pb.QueryMemberDetailResp, error) {
	l := logic.NewQueryMemberDetailLogic(ctx, s.svcCtx)
	return l.QueryMemberDetail(in)
}

// 查询用户详情（通过用户唯一标识）
func (s *MemberServer) QueryMemberDetailByIdentify(ctx context.Context, in *pb.QueryMemberDetailByIdentifyReq) (*pb.QueryMemberDetailByIdentifyResp, error) {
	l := logic.NewQueryMemberDetailByIdentifyLogic(ctx, s.svcCtx)
	return l.QueryMemberDetailByIdentify(in)
}

// 查询用户详情（通过用户名）
func (s *MemberServer) QueryMemberDetailByUsername(ctx context.Context, in *pb.QueryMemberDetailByUsernameReq) (*pb.QueryMemberDetailByUsernameResp, error) {
	l := logic.NewQueryMemberDetailByUsernameLogic(ctx, s.svcCtx)
	return l.QueryMemberDetailByUsername(in)
}

// 查询用户分页列表
func (s *MemberServer) QueryPageMemberList(ctx context.Context, in *pb.QueryPageMemberListReq) (*pb.QueryPageMemberListResp, error) {
	l := logic.NewQueryPageMemberListLogic(ctx, s.svcCtx)
	return l.QueryPageMemberList(in)
}

// 查询关键字用户分页列表
func (s *MemberServer) QueryKeywordPageMemberList(ctx context.Context, in *pb.QueryKeywordPageMemberListReq) (*pb.QueryKeywordPageMemberListResp, error) {
	l := logic.NewQueryKeywordPageMemberListLogic(ctx, s.svcCtx)
	return l.QueryKeywordPageMemberList(in)
}
