// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: main.proto

package server

import (
	"context"

	"member/rpc/internal/logic"
	"member/rpc/internal/svc"
	"member/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加用户
func (s *ServiceServer) AddMember(ctx context.Context, in *pb.AddMemberReq) (*pb.AddMemberResp, error) {
	l := logic.NewAddMemberLogic(ctx, s.svcCtx)
	return l.AddMember(in)
}

// 删除用户
func (s *ServiceServer) DeleteMember(ctx context.Context, in *pb.DeleteMemberReq) (*pb.DeleteMemberResp, error) {
	l := logic.NewDeleteMemberLogic(ctx, s.svcCtx)
	return l.DeleteMember(in)
}

// 更新用户
func (s *ServiceServer) UpdateMember(ctx context.Context, in *pb.UpdateMemberReq) (*pb.UpdateMemberResp, error) {
	l := logic.NewUpdateMemberLogic(ctx, s.svcCtx)
	return l.UpdateMember(in)
}

// 更新用户状态
func (s *ServiceServer) UpdateMemberStatus(ctx context.Context, in *pb.UpdateMemberStatusReq) (*pb.UpdateMemberStatusResp, error) {
	l := logic.NewUpdateMemberStatusLogic(ctx, s.svcCtx)
	return l.UpdateMemberStatus(in)
}

// 查询用户详情
func (s *ServiceServer) QueryMemberDetail(ctx context.Context, in *pb.QueryMemberDetailReq) (*pb.QueryMemberDetailResp, error) {
	l := logic.NewQueryMemberDetailLogic(ctx, s.svcCtx)
	return l.QueryMemberDetail(in)
}

// 查询用户分页列表
func (s *ServiceServer) QueryPageMemberList(ctx context.Context, in *pb.QueryPageMemberListReq) (*pb.QueryPageMemberListResp, error) {
	l := logic.NewQueryPageMemberListLogic(ctx, s.svcCtx)
	return l.QueryPageMemberList(in)
}

// 查询关键字用户分页列表
func (s *ServiceServer) QueryKeywordPageMemberList(ctx context.Context, in *pb.QueryKeywordPageMemberListReq) (*pb.QueryKeywordPageMemberListResp, error) {
	l := logic.NewQueryKeywordPageMemberListLogic(ctx, s.svcCtx)
	return l.QueryKeywordPageMemberList(in)
}

// 查询用户所有列表
func (s *ServiceServer) QueryMemberList(ctx context.Context, in *pb.QueryMemberListReq) (*pb.QueryMemberListResp, error) {
	l := logic.NewQueryMemberListLogic(ctx, s.svcCtx)
	return l.QueryMemberList(in)
}

// 查询关键字用户列表
func (s *ServiceServer) QueryKeywordMemberList(ctx context.Context, in *pb.QueryKeywordMemberListReq) (*pb.QueryKeywordMemberListResp, error) {
	l := logic.NewQueryKeywordMemberListLogic(ctx, s.svcCtx)
	return l.QueryKeywordMemberList(in)
}
