// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysRole = "sys_role"

// SysRole 角色表
type SysRole struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:角色唯一标识符，主键" json:"id"`           // 角色唯一标识符，主键
	Name     string    `gorm:"column:name;comment:角色名称" json:"name"`                                           // 角色名称
	Code     string    `gorm:"column:code;comment:角色编码" json:"code"`                                           // 角色编码
	Scope    string    `gorm:"column:scope;comment:角色范围" json:"scope"`                                         // 角色范围
	Sort     int32     `gorm:"column:sort;comment:排序" json:"sort"`                                             // 排序
	Status   int32     `gorm:"column:status;default:1;comment:状态，0表示禁用，1表示正常启用" json:"status"`                 // 状态，0表示禁用，1表示正常启用
	Deleted  int32     `gorm:"column:deleted;comment:逻辑删除标志，0表示未删除，1表示已删除，允许数据恢复" json:"deleted"`              // 逻辑删除标志，0表示未删除，1表示已删除，允许数据恢复
	Remark   string    `gorm:"column:remark;comment:对记录的备注信息，如特殊说明等" json:"remark"`                            // 对记录的备注信息，如特殊说明等
	CreateAt time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;comment:记录创建的时间戳" json:"create_at"`   // 记录创建的时间戳
	CreateBy string    `gorm:"column:create_by;comment:创建该记录的用户标识符" json:"create_by"`                          // 创建该记录的用户标识符
	UpdateAt time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;comment:记录最后更新的时间戳" json:"update_at"` // 记录最后更新的时间戳
	UpdateBy string    `gorm:"column:update_by;comment:最后更新该记录的用户标识符" json:"update_by"`                        // 最后更新该记录的用户标识符
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
