// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: main.proto

package server

import (
	"context"

	"authn/rpc/internal/logic"
	"authn/rpc/internal/svc"
	"authn/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// 通过用户名密码获取token
func (s *ServiceServer) QueryUsernamePasswordToken(ctx context.Context, in *pb.UsernamePasswordTokenReq) (*pb.TokenResp, error) {
	l := logic.NewQueryUsernamePasswordTokenLogic(ctx, s.svcCtx)
	return l.QueryUsernamePasswordToken(in)
}

// 刷新令牌
func (s *ServiceServer) QueryRefreshToken(ctx context.Context, in *pb.RefreshTokenReq) (*pb.TokenResp, error) {
	l := logic.NewQueryRefreshTokenLogic(ctx, s.svcCtx)
	return l.QueryRefreshToken(in)
}
