// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: main.proto

package sysmemberservice

import (
	"context"

	"member/rpc/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddSysMemberReq            = proto.AddSysMemberReq
	AddSysMemberResp           = proto.AddSysMemberResp
	DeleteSysMemberReq         = proto.DeleteSysMemberReq
	DeleteSysMemberResp        = proto.DeleteSysMemberResp
	PageSysMemberListData      = proto.PageSysMemberListData
	QueryPageSysMemberListReq  = proto.QueryPageSysMemberListReq
	QueryPageSysMemberListResp = proto.QueryPageSysMemberListResp
	QuerySysMemberDetailReq    = proto.QuerySysMemberDetailReq
	QuerySysMemberDetailResp   = proto.QuerySysMemberDetailResp
	QuerySysMemberListReq      = proto.QuerySysMemberListReq
	QuerySysMemberListResp     = proto.QuerySysMemberListResp
	SysMemberListData          = proto.SysMemberListData
	UpdateSysMemberReq         = proto.UpdateSysMemberReq
	UpdateSysMemberResp        = proto.UpdateSysMemberResp
	UpdateSysMemberStatusReq   = proto.UpdateSysMemberStatusReq
	UpdateSysMemberStatusResp  = proto.UpdateSysMemberStatusResp

	SysMemberService interface {
		// 添加用户
		AddSysMember(ctx context.Context, in *AddSysMemberReq, opts ...grpc.CallOption) (*AddSysMemberResp, error)
		// 删除用户
		DeleteSysMember(ctx context.Context, in *DeleteSysMemberReq, opts ...grpc.CallOption) (*DeleteSysMemberResp, error)
		// 更新用户
		UpdateSysMember(ctx context.Context, in *UpdateSysMemberReq, opts ...grpc.CallOption) (*UpdateSysMemberResp, error)
		// 更新用户状态
		UpdateSysMemberStatus(ctx context.Context, in *UpdateSysMemberStatusReq, opts ...grpc.CallOption) (*UpdateSysMemberStatusResp, error)
		// 查询用户详情
		QuerySysMemberDetail(ctx context.Context, in *QuerySysMemberDetailReq, opts ...grpc.CallOption) (*QuerySysMemberDetailResp, error)
		// 查询用户分页列表
		QueryPageSysMemberList(ctx context.Context, in *QueryPageSysMemberListReq, opts ...grpc.CallOption) (*QueryPageSysMemberListResp, error)
		// 查询用户所有列表
		QuerySysMemberList(ctx context.Context, in *QuerySysMemberListReq, opts ...grpc.CallOption) (*QuerySysMemberListResp, error)
	}

	defaultSysMemberService struct {
		cli zrpc.Client
	}
)

func NewSysMemberService(cli zrpc.Client) SysMemberService {
	return &defaultSysMemberService{
		cli: cli,
	}
}

// 添加用户
func (m *defaultSysMemberService) AddSysMember(ctx context.Context, in *AddSysMemberReq, opts ...grpc.CallOption) (*AddSysMemberResp, error) {
	client := proto.NewSysMemberServiceClient(m.cli.Conn())
	return client.AddSysMember(ctx, in, opts...)
}

// 删除用户
func (m *defaultSysMemberService) DeleteSysMember(ctx context.Context, in *DeleteSysMemberReq, opts ...grpc.CallOption) (*DeleteSysMemberResp, error) {
	client := proto.NewSysMemberServiceClient(m.cli.Conn())
	return client.DeleteSysMember(ctx, in, opts...)
}

// 更新用户
func (m *defaultSysMemberService) UpdateSysMember(ctx context.Context, in *UpdateSysMemberReq, opts ...grpc.CallOption) (*UpdateSysMemberResp, error) {
	client := proto.NewSysMemberServiceClient(m.cli.Conn())
	return client.UpdateSysMember(ctx, in, opts...)
}

// 更新用户状态
func (m *defaultSysMemberService) UpdateSysMemberStatus(ctx context.Context, in *UpdateSysMemberStatusReq, opts ...grpc.CallOption) (*UpdateSysMemberStatusResp, error) {
	client := proto.NewSysMemberServiceClient(m.cli.Conn())
	return client.UpdateSysMemberStatus(ctx, in, opts...)
}

// 查询用户详情
func (m *defaultSysMemberService) QuerySysMemberDetail(ctx context.Context, in *QuerySysMemberDetailReq, opts ...grpc.CallOption) (*QuerySysMemberDetailResp, error) {
	client := proto.NewSysMemberServiceClient(m.cli.Conn())
	return client.QuerySysMemberDetail(ctx, in, opts...)
}

// 查询用户分页列表
func (m *defaultSysMemberService) QueryPageSysMemberList(ctx context.Context, in *QueryPageSysMemberListReq, opts ...grpc.CallOption) (*QueryPageSysMemberListResp, error) {
	client := proto.NewSysMemberServiceClient(m.cli.Conn())
	return client.QueryPageSysMemberList(ctx, in, opts...)
}

// 查询用户所有列表
func (m *defaultSysMemberService) QuerySysMemberList(ctx context.Context, in *QuerySysMemberListReq, opts ...grpc.CallOption) (*QuerySysMemberListResp, error) {
	client := proto.NewSysMemberServiceClient(m.cli.Conn())
	return client.QuerySysMemberList(ctx, in, opts...)
}
