// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: member.proto

package server

import (
	"context"

	"status/rpc/internal/logic"
	"status/rpc/internal/svc"
	"status/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加用户登录状态
func (s *ServiceServer) AddMemberLoginStatus(ctx context.Context, in *pb.AddMemberLoginStatusReq) (*pb.AddMemberLoginStatusResp, error) {
	l := logic.NewAddMemberLoginStatusLogic(ctx, s.svcCtx)
	return l.AddMemberLoginStatus(in)
}

// 更新用户登录状态
func (s *ServiceServer) UpdateMemberLogoutStatus(ctx context.Context, in *pb.UpdateMemberLogoutStatusReq) (*pb.UpdateMemberLogoutStatusResp, error) {
	l := logic.NewUpdateMemberLogoutStatusLogic(ctx, s.svcCtx)
	return l.UpdateMemberLogoutStatus(in)
}

// 查询用户登录状态详情
func (s *ServiceServer) QueryMemberLoginStatusDetail(ctx context.Context, in *pb.QueryMemberLoginStatusDetailReq) (*pb.QueryMemberLoginStatusDetailResp, error) {
	l := logic.NewQueryMemberLoginStatusDetailLogic(ctx, s.svcCtx)
	return l.QueryMemberLoginStatusDetail(in)
}

// 查询用户登录状态分页列表
func (s *ServiceServer) QueryPageMemberLoginStatusList(ctx context.Context, in *pb.QueryPageMemberLoginStatusListReq) (*pb.QueryPageMemberLoginStatusListResp, error) {
	l := logic.NewQueryPageMemberLoginStatusListLogic(ctx, s.svcCtx)
	return l.QueryPageMemberLoginStatusList(in)
}

// 查询用户登录状态所有列表
func (s *ServiceServer) QueryMemberLoginStatusList(ctx context.Context, in *pb.QueryMemberLoginStatusListReq) (*pb.QueryMemberLoginStatusListResp, error) {
	l := logic.NewQueryMemberLoginStatusListLogic(ctx, s.svcCtx)
	return l.QueryMemberLoginStatusList(in)
}
