// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: main.proto

package server

import (
	"context"

	"authn/rpc/internal/logic/authenticationservice"
	"authn/rpc/internal/svc"
	"authn/rpc/pb"
)

type AuthenticationServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthenticationServiceServer
}

func NewAuthenticationServiceServer(svcCtx *svc.ServiceContext) *AuthenticationServiceServer {
	return &AuthenticationServiceServer{
		svcCtx: svcCtx,
	}
}

// 通过用户名密码获取token
func (s *AuthenticationServiceServer) UsernamePasswordToken(ctx context.Context, in *pb.UsernamePasswordTokenReq) (*pb.UsernamePasswordTokenResp, error) {
	l := authenticationservicelogic.NewUsernamePasswordTokenLogic(ctx, s.svcCtx)
	return l.UsernamePasswordToken(in)
}
