// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMemberLoginStatus = "sys_member_login_status"

// SysMemberLoginStatus 用户登录状态表
type SysMemberLoginStatus struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键，自增" json:"id"`                    // 主键，自增
	MemberID    int64     `gorm:"column:member_id;not null;comment:用户唯一标识符，外键关联用户表" json:"member_id"`                 // 用户唯一标识符，外键关联用户表
	Client      string    `gorm:"column:client;comment:客户端" json:"client"`                                            // 客户端
	LoginIP     string    `gorm:"column:login_ip;comment:用户最近一次登录的IP地址" json:"login_ip"`                              // 用户最近一次登录的IP地址
	LoginRegion string    `gorm:"column:login_region;comment:用户最近一次登录的地理位置" json:"login_region"`                      // 用户最近一次登录的地理位置
	LoginOs     string    `gorm:"column:login_os;comment:用户最近一次登录的操作系统" json:"login_os"`                              // 用户最近一次登录的操作系统
	LoginAt     time.Time `gorm:"column:login_at;default:CURRENT_TIMESTAMP;comment:用户最近一次登录的时间戳" json:"login_at"`     // 用户最近一次登录的时间戳
	LogoutAt    time.Time `gorm:"column:logout_at;default:1970-01-02 01:01:01;comment:用户最近一次登出的时间戳" json:"logout_at"` // 用户最近一次登出的时间戳
}

// TableName SysMemberLoginStatus's table name
func (*SysMemberLoginStatus) TableName() string {
	return TableNameSysMemberLoginStatus
}
