// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: main.proto

package server

import (
	"context"

	"member/rpc/internal/logic/sysmemberservice"
	"member/rpc/internal/svc"
	"member/rpc/proto"
)

type SysMemberServiceServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedSysMemberServiceServer
}

func NewSysMemberServiceServer(svcCtx *svc.ServiceContext) *SysMemberServiceServer {
	return &SysMemberServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加用户
func (s *SysMemberServiceServer) AddSysMember(ctx context.Context, in *proto.AddSysMemberReq) (*proto.AddSysMemberResp, error) {
	l := sysmemberservicelogic.NewAddSysMemberLogic(ctx, s.svcCtx)
	return l.AddSysMember(in)
}

// 删除用户
func (s *SysMemberServiceServer) DeleteSysMember(ctx context.Context, in *proto.DeleteSysMemberReq) (*proto.DeleteSysMemberResp, error) {
	l := sysmemberservicelogic.NewDeleteSysMemberLogic(ctx, s.svcCtx)
	return l.DeleteSysMember(in)
}

// 更新用户
func (s *SysMemberServiceServer) UpdateSysMember(ctx context.Context, in *proto.UpdateSysMemberReq) (*proto.UpdateSysMemberResp, error) {
	l := sysmemberservicelogic.NewUpdateSysMemberLogic(ctx, s.svcCtx)
	return l.UpdateSysMember(in)
}

// 更新用户状态
func (s *SysMemberServiceServer) UpdateSysMemberStatus(ctx context.Context, in *proto.UpdateSysMemberStatusReq) (*proto.UpdateSysMemberStatusResp, error) {
	l := sysmemberservicelogic.NewUpdateSysMemberStatusLogic(ctx, s.svcCtx)
	return l.UpdateSysMemberStatus(in)
}

// 查询用户详情
func (s *SysMemberServiceServer) QuerySysMemberDetail(ctx context.Context, in *proto.QuerySysMemberDetailReq) (*proto.QuerySysMemberDetailResp, error) {
	l := sysmemberservicelogic.NewQuerySysMemberDetailLogic(ctx, s.svcCtx)
	return l.QuerySysMemberDetail(in)
}

// 查询用户分页列表
func (s *SysMemberServiceServer) QueryPageSysMemberList(ctx context.Context, in *proto.QueryPageSysMemberListReq) (*proto.QueryPageSysMemberListResp, error) {
	l := sysmemberservicelogic.NewQueryPageSysMemberListLogic(ctx, s.svcCtx)
	return l.QueryPageSysMemberList(in)
}

// 查询用户所有列表
func (s *SysMemberServiceServer) QuerySysMemberList(ctx context.Context, in *proto.QuerySysMemberListReq) (*proto.QuerySysMemberListResp, error) {
	l := sysmemberservicelogic.NewQuerySysMemberListLogic(ctx, s.svcCtx)
	return l.QuerySysMemberList(in)
}
